// <auto-generated />
using System;
using Escuela.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escuela.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211007161146_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Escuela.Dominio.Tbl_Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("credits")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseId");

                    b.ToTable("Tbl_Course");
                });

            modelBuilder.Entity("Escuela.Dominio.Tbl_Enrollment", b =>
                {
                    b.Property<int>("enrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FK_IdCoursecourseId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_IdStudentstudendId")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.Property<int>("studendId")
                        .HasColumnType("int");

                    b.HasKey("enrollmentId");

                    b.HasIndex("FK_IdCoursecourseId");

                    b.HasIndex("FK_IdStudentstudendId");

                    b.ToTable("Tbl_Enrollment");
                });

            modelBuilder.Entity("Escuela.Dominio.Tbl_Student", b =>
                {
                    b.Property<int>("studendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("enrollmentsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstMidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studendId");

                    b.ToTable("Tbl_Student");
                });

            modelBuilder.Entity("Escuela.Dominio.Tbl_Enrollment", b =>
                {
                    b.HasOne("Escuela.Dominio.Tbl_Course", "FK_IdCourse")
                        .WithMany("FK_IdCourse")
                        .HasForeignKey("FK_IdCoursecourseId");

                    b.HasOne("Escuela.Dominio.Tbl_Student", "FK_IdStudent")
                        .WithMany("FK_IdStudent")
                        .HasForeignKey("FK_IdStudentstudendId");

                    b.Navigation("FK_IdCourse");

                    b.Navigation("FK_IdStudent");
                });

            modelBuilder.Entity("Escuela.Dominio.Tbl_Course", b =>
                {
                    b.Navigation("FK_IdCourse");
                });

            modelBuilder.Entity("Escuela.Dominio.Tbl_Student", b =>
                {
                    b.Navigation("FK_IdStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
