//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionNotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public decimal lab1 { get; set; }
        public decimal lab2 { get; set; }
        public decimal lab3 { get; set; }
        public decimal par1 { get; set; }
        public decimal par2 { get; set; }
        public decimal par3 { get; set; }
        public Nullable<decimal> nota { get; set; }
    }
}
